---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "chart.fullname" . }}-api
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}
      release: {{ .Release.Name }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}
        chart: {{ include "chart.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image | quote }}
          ports:
            - name: http
              containerPort: 8080
