---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}-api
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: api
spec:
  selector:
    app: {{ include "chart.name" . }}
    release: {{ .Release.Name }}
    component: api
  ports:
    - port: 8080
      targetPort: http
      name: http
  type: ClusterIP
